[package]
name = "use_lib"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
metron_core={path = "../../crates/metron_core" }
metron_library={path = "../../crates/metron_library" }
