[package]
name = "metron_library"
version = "0.0.1"
authors = ["A_Hibi <bb.is.what.he.believes@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
metron_core = {path = "../metron_core"}